"""Constants for Metra Tracker integration."""

DOMAIN = "metra_tracker"
DEFAULT_NAME = "Metra UP-W Arrivals"
DEFAULT_SCAN_INTERVAL = 30  # 30 seconds
CONF_USERNAME = "username"
CONF_PASSWORD = "password"

METRA_LINES = {
    "BNSF": "BNSF",
    "HC": "Heritage Corridor",
    "ME": "Metra Electric",
    "MD-N": "Milwaukee District North",
    "MD-W": "Milwaukee District West",
    "NCS": "North Central Service",
    "RI": "Rock Island",
    "SWS": "SouthWest Service",
    "UP-N": "Union Pacific North",
    "UP-NW": "Union Pacific Northwest",
    "UP-W": "Union Pacific West",
}

METRA_STOPS_BY_LINE = {
    "BNSF": [
        "AURORA",
        "HALSTED",
        "BNWESTERN",
        "ROUTE59",
        "CICERO",
        "NAPERVILLE",
        "LISLE",
        "BELMONT",
        "MAINST-DG",
        "BERWYN",
        "FAIRVIEWDG",
        "HARLEM",
        "WESTMONT",
        "RIVERSIDE",
        "CLARNDNHIL",
        "BROOKFIELD",
        "WHINSDALE",
        "HINSDALE",
        "HIGHLANDS",
        "WESTSPRING",
        "STONEAVE",
        "LAGRANGE",
        "CONGRESSPK",
        "HOLLYWOOD",
        "LAVERGNE",
        "CUS",
    ],
    "HC": ["JOLIET", "LOCKPORT", "ROMEOVILLE", "LEMONT", "WILLOWSPRN", "SUMMIT", "CUS"],
    "MD-N": [
        "CUS",
        "FOXLAKE",
        "INGLESIDE",
        "LONGLAKE",
        "WESTERNAVE",
        "ROUNDLAKE",
        "GRAYSLAKE",
        "HEALY",
        "GRAYLAND",
        "MAYFAIR",
        "PRAIRIEXNG",
        "LIBERTYVIL",
        "FORESTGLEN",
        "EDGEBROOK",
        "MORTONGRV",
        "GOLF",
        "GLENVIEW",
        "NGLENVIEW",
        "NBROOK",
        "LAKECOOKRD",
        "DEERFIELD",
        "LAKEFRST",
    ],
    "MD-W": [
        "ELGIN",
        "NATIONALS",
        "BARTLETT",
        "HANOVERP",
        "GRAND-CIC",
        "SCHAUM",
        "HANSONPK",
        "ROSELLE",
        "MEDINAH",
        "MARS",
        "ITASCA",
        "WOODDALE",
        "BENSENVIL",
        "FRANKLIN",
        "MANNHEIM",
        "RIVERGROVE",
        "ELMWOODPK",
        "MONTCLARE",
        "GALEWOOD",
        "WESTERNAVE",
        "CUS",
        "BIGTIMBER",
    ],
    "ME": [
        "BLUEISLAND",
        "BURROAK",
        "ASHLAND",
        "RACINE",
        "WPULLMAN",
        "STEWARTRID",
        "STATEST",
        "93RD-SC",
        "87TH-SC",
        "83RD-SC",
        "79TH-SC",
        "WINDSORPK",
        "SOUTHSHORE",
        "BRYNMAWR",
        "STONYISLND",
        "UNIVERSITY",
        "RICHTON",
        "MATTESON",
        "211TH-UP",
        "OLYMPIA",
        "FLOSSMOOR",
        "HOMEWOOD",
        "CALUMET",
        "HAZELCREST",
        "HARVEY",
        "147TH-UP",
        "IVANHOE",
        "RIVERDALE",
        "KENSINGTN",
        "111TH-UP",
        "107TH-UP",
        "103RD-UP",
        "91ST-UP",
        "83RD-UP",
        "79TH-UP",
        "75TH-UP",
        "63RD-UP",
        "59TH-UP",
        "55-56-57TH",
        "51ST-53RD",
        "47TH-UP",
        "27TH-UP",
        "MCCORMICK",
        "18TH-UP",
        "MUSEUM",
        "VANBUREN",
        "MILLENNIUM",
    ],
    "NCS": [
        "ANTIOCH",
        "LAKEVILLA",
        "ROUNDLKBCH",
        "NCSGRAYSLK",
        "PRAIRCROSS",
        "MUNDELEIN",
        "VERNON",
        "PRAIRIEVW",
        "BUFFGROVE",
        "WHEELING",
        "PROSPECTHG",
        "OHARE",
        "ROSEMONT",
        "SCHILLERPK",
        "FRANKLINPK",
        "RIVERGROVE",
        "WESTERNAVE",
        "CUS",
    ],
    "RI": [
        "JOLIET",
        "NEWLENOX",
        "MOKENA",
        "HICKORYCRK",
        "TINLEY80TH",
        "TINLEYPARK",
        "OAKFOREST",
        "MIDLOTHIAN",
        "ROBBINS",
        "VERMONT",
        "PRAIRIEST",
        "123RD-BEV",
        "119TH-BEV",
        "115TH-BEV",
        "111TH-BEV",
        "107TH-BEV",
        "103RD-BEV",
        "99TH-BEV",
        "95TH-BEV",
        "91ST-BEV",
        "BRAINERD",
        "WASHHGTS",
        "LONGWOOD",
        "GRESHAM",
        "35TH",
        "LSS",
    ],
    "SWS": [
        "MANHATTAN",
        "LARAWAY",
        "179TH-SWS",
        "153RD-SWS",
        "143RD-SWS",
        "PALOSPARK",
        "PALOSHTS",
        "WORTH",
        "CHICRIDGE",
        "OAKLAWN",
        "ASHBURN",
        "WRIGHTWOOD",
        "CUS",
    ],
    "UP-N": [
        "WAUKEGAN",
        "NCHICAGO",
        "GRTLAKES",
        "LAKEBLUFF",
        "LKFOREST",
        "FTSHERIDAN",
        "HIGHWOOD",
        "HIGHLANDPK",
        "RAVINIA",
        "BRAESIDE",
        "GLENCOE",
        "HUBARDWOOD",
        "WINNETKA",
        "INDIANHILL",
        "KENILWORTH",
        "WILMETTE",
        "CENTRALST",
        "EVANSTON",
        "MAINST",
        "ROGERPK",
        "PETERSON",
        "RAVENSWOOD",
        "ZION",
        "CLYBOURN",
        "WINTHROP",
        "OTC",
        "KENOSHA",
    ],
    "UP-NW": [
        "OTC",
        "CLYBOURN",
        "MCHENRY",
        "IRVINGPK",
        "JEFFERSONP",
        "NORWOODP",
        "EDISONPK",
        "PARKRIDGE",
        "DEEROAD",
        "DESPLAINES",
        "CUMBERLAND",
        "MTPROSPECT",
        "ARLINGTNHT",
        "ARLINGTNPK",
        "PALATINE",
        "BARRINGTON",
        "FOXRG",
        "CARY",
        "PINGREE",
        "CRYSTAL",
        "GLADSTONEP",
        "WOODSTOCK",
        "HARVARD",
    ],
    "UP-W": [
        "ELBURN",
        "LAFOX",
        "GENEVA",
        "WCHICAGO",
        "WINFIELD",
        "WHEATON",
        "COLLEGEAVE",
        "GLENELLYN",
        "LOMBARD",
        "VILLAPARK",
        "ELMHURST",
        "BERKELEY",
        "BELLWOOD",
        "MELROSEPK",
        "MAYWOOD",
        "RIVRFOREST",
        "OAKPARK",
        "KEDZIE",
        "OTC",
    ],
}
